CREATE TABLE UNF_COURSE_SELECTION (
  Student_ID VARCHAR2(10),
  Student_Name VARCHAR2(40),
  Student_Dept VARCHAR2(20),
  Student_Contact VARCHAR2(15),
  Student_Email VARCHAR2(40),
  CGPA NUMBER(3,2),
  Advisor_ID VARCHAR2(10),
  Advisor_Name VARCHAR2(40),
  Advisor_Email VARCHAR2(40),
  Advisor_Contact VARCHAR2(15),
  Course_ID VARCHAR2(10),
  Course_Name VARCHAR2(40),
  Course_Credit VARCHAR2(10),
  Teacher_ID VARCHAR2(10),
  Teacher_Name VARCHAR2(40),
  Teacher_Email VARCHAR2(40),
  Teacher_Address VARCHAR2(50),
  Fee_ID VARCHAR2(10),
  Fee_Amount VARCHAR2(20),
  Feedback_ID VARCHAR2(10),
  Feedback_Report VARCHAR2(40)
);
