CREATE TABLE "STUDENT_1NF"
( 
    "S_ID" VARCHAR2(10) NOT NULL ENABLE,
    "S_NAME" VARCHAR2(40),
    "S_DEPT" VARCHAR2(10),
    "S_EMAIL" VARCHAR2(30),
    "CGPA" NUMBER NOT NULL ENABLE,
    CONSTRAINT "STUDENT_1NF_PK" PRIMARY KEY ("S_ID") ENABLE
);

CREATE TABLE "TEACHER_1NF"
( 
    "T_ID" VARCHAR2(10) NOT NULL ENABLE,
    "T_NAME" VARCHAR2(40),
    "T_EMAIL" VARCHAR2(30),
    "T_ADDRESS" VARCHAR2(40),
    CONSTRAINT "TEACHER_1NF_PK" PRIMARY KEY ("T_ID") ENABLE
);

CREATE TABLE "COURSE_1NF"
( 
    "C_ID" VARCHAR2(10) NOT NULL ENABLE,
    "C_NAME" VARCHAR2(40),
    "C_CREDIT" VARCHAR2(10),
    CONSTRAINT "COURSE_1NF_PK" PRIMARY KEY ("C_ID") ENABLE
);

CREATE TABLE "COURSE_ENROLLMENT_1NF"
( 
    "C_ID" VARCHAR2(10) NOT NULL ENABLE,
    "S_ID" VARCHAR2(10) NOT NULL ENABLE,
    CONSTRAINT "COURSE_ENROLLMENT_1NF_PK" PRIMARY KEY ("C_ID", "S_ID") ENABLE,
    CONSTRAINT "COURSE_ENROLLMENT_1NF_FK1" FOREIGN KEY ("C_ID")
        REFERENCES "COURSE_1NF" ("C_ID") ENABLE,
    CONSTRAINT "COURSE_ENROLLMENT_1NF_FK2" FOREIGN KEY ("S_ID")
        REFERENCES "STUDENT_1NF" ("S_ID") ENABLE
);
