CREATE TABLE "STUDENT_2NF"
( 
    "S_ID" VARCHAR2(10) NOT NULL ENABLE,
    "S_NAME" VARCHAR2(40),
    "S_DEPT" VARCHAR2(10),
    "S_EMAIL" VARCHAR2(30),
    "CGPA" NUMBER NOT NULL ENABLE,
    CONSTRAINT "STUDENT_2NF_PK" PRIMARY KEY ("S_ID") ENABLE
);

CREATE TABLE "COURSE_2NF"
( 
    "C_ID" VARCHAR2(10) NOT NULL ENABLE,
    "C_NAME" VARCHAR2(40),
    "C_CREDIT" VARCHAR2(10),
    CONSTRAINT "COURSE_2NF_PK" PRIMARY KEY ("C_ID") ENABLE
);

CREATE TABLE "ENROLLMENT_2NF"
( 
    "C_ID" VARCHAR2(10) NOT NULL ENABLE,
    "S_ID" VARCHAR2(10) NOT NULL ENABLE,
    CONSTRAINT "ENROLLMENT_2NF_PK" PRIMARY KEY ("C_ID", "S_ID") ENABLE,
    CONSTRAINT "ENROLLMENT_2NF_FK1" FOREIGN KEY ("C_ID")
        REFERENCES "COURSE_2NF" ("C_ID") ENABLE,
    CONSTRAINT "ENROLLMENT_2NF_FK2" FOREIGN KEY ("S_ID")
        REFERENCES "STUDENT_2NF" ("S_ID") ENABLE
);

CREATE TABLE "ADVISOR_2NF"
( 
    "A_ID" VARCHAR2(10) NOT NULL ENABLE,
    "A_NAME" VARCHAR2(40),
    "A_EMAIL" VARCHAR2(30),
    "A_CONTACT" VARCHAR2(15),
    CONSTRAINT "ADVISOR_2NF_PK" PRIMARY KEY ("A_ID") ENABLE
);

CREATE TABLE "ADVISOR_ASSIGNMENT_2NF"
( 
    "A_ID" VARCHAR2(10) NOT NULL ENABLE,
    "S_ID" VARCHAR2(10) NOT NULL ENABLE,
    CONSTRAINT "ADVISOR_ASSIGNMENT_2NF_PK" PRIMARY KEY ("A_ID", "S_ID") ENABLE,
    CONSTRAINT "ADVISOR_ASSIGNMENT_2NF_FK1" FOREIGN KEY ("A_ID")
        REFERENCES "ADVISOR_2NF" ("A_ID") ENABLE,
    CONSTRAINT "ADVISOR_ASSIGNMENT_2NF_FK2" FOREIGN KEY ("S_ID")
        REFERENCES "STUDENT_2NF" ("S_ID") ENABLE
);
