CREATE TABLE "STUDENT_3NF"
( 
    "S_ID" VARCHAR2(10) NOT NULL ENABLE,
    "S_NAME" VARCHAR2(40),
    "S_DEPT" VARCHAR2(10),
    "S_EMAIL" VARCHAR2(30),
    "CGPA" NUMBER NOT NULL ENABLE,
    CONSTRAINT "STUDENT_3NF_PK" PRIMARY KEY ("S_ID") ENABLE
);

CREATE TABLE "COURSE_3NF"
( 
    "C_ID" VARCHAR2(10) NOT NULL ENABLE,
    "C_NAME" VARCHAR2(40),
    "C_CREDIT" VARCHAR2(10),
    CONSTRAINT "COURSE_3NF_PK" PRIMARY KEY ("C_ID") ENABLE
);

CREATE TABLE "ENROLLMENT_3NF"
( 
    "C_ID" VARCHAR2(10) NOT NULL ENABLE,
    "S_ID" VARCHAR2(10) NOT NULL ENABLE,
    CONSTRAINT "ENROLLMENT_3NF_PK" PRIMARY KEY ("C_ID", "S_ID") ENABLE,
    CONSTRAINT "ENROLLMENT_3NF_FK1" FOREIGN KEY ("C_ID")
        REFERENCES "COURSE_3NF" ("C_ID") ENABLE,
    CONSTRAINT "ENROLLMENT_3NF_FK2" FOREIGN KEY ("S_ID")
        REFERENCES "STUDENT_3NF" ("S_ID") ENABLE
);

CREATE TABLE "ADVISOR_3NF"
( 
    "A_ID" VARCHAR2(10) NOT NULL ENABLE,
    "A_NAME" VARCHAR2(40),
    "A_EMAIL" VARCHAR2(30),
    "A_CONTACT" VARCHAR2(15),
    CONSTRAINT "ADVISOR_3NF_PK" PRIMARY KEY ("A_ID") ENABLE
);

CREATE TABLE "ADVISOR_ASSIGNMENT_3NF"
( 
    "A_ID" VARCHAR2(10) NOT NULL ENABLE,
    "S_ID" VARCHAR2(10) NOT NULL ENABLE,
    CONSTRAINT "ADVISOR_ASSIGNMENT_3NF_PK" PRIMARY KEY ("A_ID", "S_ID") ENABLE,
    CONSTRAINT "ADVISOR_ASSIGNMENT_3NF_FK1" FOREIGN KEY ("A_ID")
        REFERENCES "ADVISOR_3NF" ("A_ID") ENABLE,
    CONSTRAINT "ADVISOR_ASSIGNMENT_3NF_FK2" FOREIGN KEY ("S_ID")
        REFERENCES "STUDENT_3NF" ("S_ID") ENABLE
);

CREATE TABLE "FEES_3NF"
( 
    "FEE_ID" VARCHAR2(10) NOT NULL ENABLE,
    "FEE_AMOUNT" VARCHAR2(20),
    "C_ID" VARCHAR2(10),
    CONSTRAINT "FEES_3NF_PK" PRIMARY KEY ("FEE_ID") ENABLE,
    CONSTRAINT "FEES_3NF_CK1" CHECK (FEE_AMOUNT >= 0) ENABLE,
    CONSTRAINT "FEES_3NF_FK" FOREIGN KEY ("C_ID")
        REFERENCES "COURSE_3NF" ("C_ID") ENABLE
);
 