-- Create STUDENT table with unique constraint names
CREATE TABLE "STUDENT70"
( 
    "S_ID" VARCHAR2(10) NOT NULL ENABLE,
    "S_NAME" VARCHAR2(40),
    "S_DEPT" VARCHAR2(10),
    "S_CONTACT" VARCHAR2(15),
    "S_EMAIL" VARCHAR2(30),
    "CGPA" NUMBER NOT NULL ENABLE,
    CONSTRAINT "STUDENT70_PK" PRIMARY KEY ("S_ID") ENABLE
)
/

-- Create TEACHER table with unique constraint names
CREATE TABLE "TEACHER70"
( 
    "T_ID" VARCHAR2(10) NOT NULL ENABLE,
    "T_NAME" VARCHAR2(40),
    "T_EMAIL" VARCHAR2(30),
    "T_ADDRESS" VARCHAR2(40),
    CONSTRAINT "TEACHER70_PK" PRIMARY KEY ("T_ID") ENABLE
)
/

-- Create COURSE table with unique constraint names
CREATE TABLE "COURSE70"
( 
    "C_ID" VARCHAR2(10) NOT NULL ENABLE,
    "C_NAME" VARCHAR2(40),
    "C_CREDIT" VARCHAR2(10),
    CONSTRAINT "COURSE70_PK" PRIMARY KEY ("C_ID") ENABLE
)
/

-- Create COURSE_ENROLLMENT table with unique constraint names
CREATE TABLE "COURSE_ENROLLMENT70"
( 
    "C_ID" VARCHAR2(10) NOT NULL ENABLE,
    "S_ID" VARCHAR2(10) NOT NULL ENABLE,
    CONSTRAINT "COURSE_ENROLLMENT70_PK" PRIMARY KEY ("C_ID", "S_ID") ENABLE,
    CONSTRAINT "COURSE_ENROLLMENT70_FK1" FOREIGN KEY ("C_ID")
        REFERENCES "COURSE70" ("C_ID") ENABLE,
    CONSTRAINT "COURSE_ENROLLMENT70_FK2" FOREIGN KEY ("S_ID")
        REFERENCES "STUDENT70" ("S_ID") ENABLE
)
/

-- Create ADVISOR table with unique constraint names
CREATE TABLE "ADVISOR70"
( 
    "A_ID" VARCHAR2(10) NOT NULL ENABLE,
    "A_NAME" VARCHAR2(40),
    "A_EMAIL" VARCHAR2(30),
    "A_CONTACT" VARCHAR2(15),
    CONSTRAINT "ADVISOR70_PK" PRIMARY KEY ("A_ID") ENABLE
)
/

-- Create ADVISOR_ASSIGNMENT table with unique constraint names
CREATE TABLE "ADVISOR_ASSIGNMENT70"
( 
    "A_ID" VARCHAR2(10) NOT NULL ENABLE,
    "S_ID" VARCHAR2(10) NOT NULL ENABLE,
    CONSTRAINT "ADVISOR_ASSIGNMENT70_PK" PRIMARY KEY ("A_ID", "S_ID") ENABLE,
    CONSTRAINT "ADVISOR_ASSIGNMENT70_FK1" FOREIGN KEY ("A_ID")
        REFERENCES "ADVISOR70" ("A_ID") ENABLE,
    CONSTRAINT "ADVISOR_ASSIGNMENT70_FK2" FOREIGN KEY ("S_ID")
        REFERENCES "STUDENT70" ("S_ID") ENABLE
)
/

-- Create FEES table with unique constraint names
CREATE TABLE "FEES70"
( 
    "FEE_ID" VARCHAR2(10) NOT NULL ENABLE,
    "FEE_AMOUNT" VARCHAR2(20),
    "C_ID" VARCHAR2(10),
    CONSTRAINT "FEES70_PK" PRIMARY KEY ("FEE_ID") ENABLE,
    CONSTRAINT "FEES70_CK1" CHECK (FEE_AMOUNT >= 0) ENABLE,
    CONSTRAINT "FEES70_FK" FOREIGN KEY ("C_ID")
        REFERENCES "COURSE70" ("C_ID") ENABLE
)
/

-- Create FEEDBACK table with unique constraint names
CREATE TABLE "FEEDBACK70"
( 
    "FD_ID" VARCHAR2(10) NOT NULL ENABLE,
    "FD_REPORT" VARCHAR2(40),
    "S_ID" VARCHAR2(10),
    "C_ID" VARCHAR2(10),
    "A_ID" VARCHAR2(10),
    CONSTRAINT "FEEDBACK70_PK" PRIMARY KEY ("FD_ID") ENABLE,
    CONSTRAINT "FEEDBACK70_FK1" FOREIGN KEY ("S_ID")
        REFERENCES "STUDENT70" ("S_ID") ENABLE,
    CONSTRAINT "FEEDBACK70_FK2" FOREIGN KEY ("C_ID")
        REFERENCES "COURSE70" ("C_ID") ENABLE,
    CONSTRAINT "FEEDBACK70_FK3" FOREIGN KEY ("A_ID")
        REFERENCES "ADVISOR70" ("A_ID") ENABLE
)
/
